---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: stop container
      shell: docker stop vkapp
    - name: remove container
      shell: docker rm vkapp
    - name: remove docker image
      shell: docker rmi vilaschavan80/vkapp
    - name: create new container
      shell: docker run -itd --name vkapp -p 8081:8080 vilaschavan80/vkapp
